---
name: Build and Push (0)

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Download poetry installer
      run: |
        wget -q -S -O install.py https://install.python-poetry.org

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push (3.12.3-bookworm, 3.12-bookworm, 3-bookworm, bookworm, 3.12.3, 3.12, 3, latest)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
        push: true
        tags: weastur/poetry:latest-python-3.12.3-bookworm,weastur/poetry:1.8.3-python-3.12.3-bookworm,weastur/poetry:latest-python-3.12-bookworm,weastur/poetry:1.8.3-python-3.12-bookworm,weastur/poetry:latest-python-3-bookworm,weastur/poetry:1.8.3-python-3-bookworm,weastur/poetry:latest-python-bookworm,weastur/poetry:1.8.3-python-bookworm,weastur/poetry:latest-python-3.12.3,weastur/poetry:1.8.3-python-3.12.3,weastur/poetry:latest-python-3.12,weastur/poetry:1.8.3-python-3.12,weastur/poetry:latest-python-3,weastur/poetry:1.8.3-python-3,weastur/poetry:latest-python-latest,weastur/poetry:1.8.3-python-latest,weastur/poetry:latest
        build-args: |
          BASE_IMAGE_VERSION=3.12.3-bookworm
          POETRY_VERSION=1.8.3
