---
name: Build and Push (4)

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Download poetry installer
      run: |
        wget -q -S -O install.py https://install.python-poetry.org

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push (3.12.3-alpine3.20, 3.12-alpine3.20, 3-alpine3.20, alpine3.20, 3.12.3-alpine, 3.12-alpine, 3-alpine, alpine)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x
        push: true
        tags: weastur/poetry:latest-python-3.12.3-alpine3.20,weastur/poetry:1.8.3-python-3.12.3-alpine3.20,weastur/poetry:latest-python-3.12-alpine3.20,weastur/poetry:1.8.3-python-3.12-alpine3.20,weastur/poetry:latest-python-3-alpine3.20,weastur/poetry:1.8.3-python-3-alpine3.20,weastur/poetry:latest-python-alpine3.20,weastur/poetry:1.8.3-python-alpine3.20,weastur/poetry:latest-python-3.12.3-alpine,weastur/poetry:1.8.3-python-3.12.3-alpine,weastur/poetry:latest-python-3.12-alpine,weastur/poetry:1.8.3-python-3.12-alpine,weastur/poetry:latest-python-3-alpine,weastur/poetry:1.8.3-python-3-alpine,weastur/poetry:latest-python-alpine,weastur/poetry:1.8.3-python-alpine
        build-args: |
          BASE_IMAGE_VERSION=3.12.3-alpine3.20
          POETRY_VERSION=1.8.3
